#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-Factory
version:      0.81
version_from: lib/Class/DBI/Factory.pm
installdirs:  site
requires:
    Class::DBI:                    0.96
    Apache::Constants:             0
    Email::Send:                   0
    Apache::Request:               0
    AppConfig:                     0
    Error:                         0
    Ima::DBI:                      0.33
    Test::Exception:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
