#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-Factory
version:      0.74
version_from: lib/Class/DBI/Factory.pm
installdirs:  site
requires:
    Class::DBI:                    0.92
    AppConfig:                     0
    Data::Dumper:                  0
    Class::DBI::FromCGI:           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
