#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-Factory
version:      0.76
version_from: lib/Class/DBI/Factory.pm
installdirs:  site
requires:
    Class::DBI::FromCGI:           0
    Ima::DBI:                      0.33
    Class::DBI:                    0.96
    AppConfig:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
